/* Populate de tablas */
INSERT INTO regiones(id, nombre) VALUES (1, 'Sudamérica');
INSERT INTO regiones(id, nombre) VALUES (2, 'Centroamérica');
INSERT INTO regiones(id, nombre) VALUES (3, 'Norteamérica');
INSERT INTO regiones(id, nombre) VALUES (4, 'Europa');
INSERT INTO regiones(id, nombre) VALUES (5, 'Asia');
INSERT INTO regiones(id, nombre) VALUES (6, 'África');
INSERT INTO regiones(id, nombre) VALUES (7, 'Oceanía');
INSERT INTO regiones(id, nombre) VALUES (8, 'Antártida');
INSERT INTO anuncios (region_id, titulo, historia, create_at) VALUES (1, 'Titulo1', 'Esta es la historia 1', '01/12/2001');
INSERT INTO anuncios (region_id, titulo, historia, create_at) VALUES (2, 'Titulo2', 'Esta es la historia 2', '02/12/2001');
INSERT INTO anuncios (region_id, titulo, historia, create_at) VALUES (4, 'Titulo3', 'Esta es la historia 3', '03/12/2001');
INSERT INTO anuncios (region_id, titulo, historia, create_at) VALUES (4, 'Titulo4', 'Esta es la historia 3', '03/12/2001');
INSERT INTO anuncios (region_id, titulo, historia, create_at) VALUES (4, 'Titulo5', 'Esta es la historia 3', '03/12/2001');
INSERT INTO anuncios (region_id, titulo, historia, create_at) VALUES (3, 'Titulo6', 'Esta es la historia 3', '03/12/2001');
INSERT INTO anuncios (region_id, titulo, historia, create_at) VALUES (3, 'Titulo7', 'Esta es la historia 3', '03/12/2001');
INSERT INTO anuncios (region_id, titulo, historia, create_at) VALUES (3, 'Titulo8', 'Esta es la historia 3', '03/12/2001');
INSERT INTO anuncios (region_id, titulo, historia, create_at) VALUES (3, 'Titulo9', 'Esta es la historia 3', '03/12/2001');
INSERT INTO anuncios (region_id, titulo, historia, create_at) VALUES (5, 'Titulo10', 'Esta es la historia 3', '03/12/2001');
INSERT INTO anuncios (region_id, titulo, historia, create_at) VALUES (6, 'Titulo11', 'Esta es la historia 3', '03/12/2001');
INSERT INTO anuncios (region_id, titulo, historia, create_at) VALUES (7, 'Titulo12', 'Esta es la historia 3', '03/12/2001');